insert into `categories` (`nom`) values 
('barrages'),
('comptabilité'),
('aéroport'),
('galerie d\'art'),
('atm'),
('boulangerie'),
('banque'),
('magasin de vélos'),
('librairie'),
('Allée de bowling'),
('station de bus'),
('café'),
('camping'),
('concessionnaire'),
('location de voiture'),
('réparation automobile'),
('Lave-Auto'),
('cimetière'),
('mosquée'),
('magasin de vêtements'),
('épicerie'),
('tribunal'),
('dentiste'),
('grand magasin'),
('médecin'),
('électricien'),
('ambassade'),
('caserne de pompiers'),
('poste de police'),
('fleuriste'),
('Magasin de meubles'),
('station-essence'),
('Gym'),
('soin des cheveux'),
('magasin d\'articles pour la maison'),
('hôpital'),
('Agence d\'assurance'),
('bijouterie'),
('blanchisserie'),
('avocat'),
('bibliothèque'),
('hébergement'),
('musée'),
('peintre'),
('parc'),
('parking'),
('pharmacie'),
('physiothérapeute'),
('plombier'),
('bureau de poste'),
('restaurant'),
('école'),
('centre commercial'),
('stade'),
('espace de rangement'),
('magasin'),
('station de métro'),
('supermarché'),
('station de taxi'),
('agence de voyage'),
('zoo')